# Generated by Django 4.0.5 on 2022-06-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.TextField(null=True, verbose_name='category about'),
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='category image'),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(null=True, verbose_name='category price'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Category name'),
        ),
    ]
