# Generated by Django 4.0.5 on 2022-06-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_about_category_img_category_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='people name')),
                ('surname', models.CharField(max_length=30, verbose_name='people surname')),
                ('img', models.ImageField(null=True, upload_to='media', verbose_name='people image')),
            ],
            options={
                'verbose_name': 'people',
                'verbose_name_plural': 'people',
            },
        ),
    ]
